
name: Scan for Secrets

on:
  push:
    branches: [ $default-branch ]
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
